# Generated by Django 4.2.3 on 2023-07-21 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_wallet_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        choices=[
                            ("Orange", "Orange"),
                            ("Banana", "Banana"),
                            ("Mango", "Mango"),
                            ("Apple", "Apple"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField()),
            ],
            options={"verbose_name": "Purchase", "verbose_name_plural": "Purchases",},
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_item",
                    models.CharField(
                        choices=[
                            ("Orange", "Orange"),
                            ("Banana", "Banana"),
                            ("Mango", "Mango"),
                            ("Apple", "Apple"),
                        ],
                        max_length=10,
                    ),
                ),
                ("available_quantity", models.IntegerField()),
            ],
            options={"verbose_name": "Stock", "verbose_name_plural": "Stocks",},
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
