# Generated by Django 4.2.3 on 2023-07-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_purchase_item_alter_stock_available_item"),
    ]

    operations = [
        migrations.DeleteModel(name="Purchase",),
        migrations.DeleteModel(name="Stock",),
    ]
