# Generated by Django 4.2.3 on 2023-07-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_delete_purchase_delete_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet", old_name="amount", new_name="balance",
        ),
    ]
