# Generated by Django 4.2.3 on 2023-07-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_wallet2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("watch_ad", "watch_ad"),
                            ("use_points", "use_points"),
                            ("no_ad", "no_ad"),
                        ],
                        max_length=255,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.wallet2"
                    ),
                ),
            ],
        ),
    ]
