# Generated by Django 4.2.3 on 2023-07-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_transaction2"),
    ]

    operations = [
        migrations.DeleteModel(name="Transaction",),
    ]
