# Generated by Django 4.2.3 on 2023-07-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_delete_transaction"),
    ]

    operations = [
        migrations.DeleteModel(name="Wallet",),
    ]
