# Generated by Django 4.2.3 on 2023-07-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_delete_wallet"),
    ]

    operations = [
        migrations.RenameModel(old_name="Transaction2", new_name="Transaction",),
        migrations.RenameModel(old_name="Wallet2", new_name="Wallet",),
    ]
